name: order-manager

services:
  api:
    container_name: order-manager
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 8080:8080
    volumes:
      - ./bin/Release/net8.0/linux-x64/publish:/app
    working_dir: /app
    command: ["dotnet", "OrderManager.Api.dll"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
